server:
  port: 3344
spring:
  application:
    name: cloud-config-server-3344
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/huo1362120194/springcloud-config.git
          username: huo1362120194@163.com
          password: wangshikun19903
          search-path:
            - springcloud-config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: cloud-config-server-3344
    prefer-ip-address: true
    # 客户端向服务端发送心跳的时间间隔
    lease-renewal-interval-in-seconds: 30
    # 服务端在收到最后一次心跳后等待时间上限，超时将服务剔除
    lease-expiration-duration-in-seconds: 90
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
