server:
  port: 9001
spring:
  application:
    name: cloud-provider-payment-9001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: cloud-provider-payment-9001
    prefer-ip-address: true
    # 客户端向服务端发送心跳的时间间隔
    lease-renewal-interval-in-seconds: 30
    # 服务端在收到最后一次心跳后等待时间上限，超时将服务剔除
    lease-expiration-duration-in-seconds: 90
management:
  endpoints:
    web:
      exposure:
        # 暴露hystrix监控端点
        include: '*'
